name: Netflix Pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            VITE_APP_TMDB_V3_API_KEY=${{ secrets.API_KEY }}
#          push: true
          tags: wahabkas/netflix:${{ github.sha }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with: 
            image-ref: 'wahabkas/netflix:${{ github.sha }}'
            format: 'table'
            severity: 'CRITICAL,HIGH'
            exit-code: '1'
